import { ArrowRight, CheckCircle2, Upload } from "lucide-react";

import { RecentMatches } from "@/components/recent-matches";
import { ButtonLink } from "@/components/ui/button";

const workflow = [
  "Upload",
  "Calibrate",
  "Select Player",
  "View Analytics",
] as const;

export default function DashboardPage() {
  return (
    <div className="space-y-8">
      <section className="rounded-md border border-court-line bg-white p-6 shadow-panel">
        <div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wide text-court-green">
              Court4 MVP
            </p>
            <h1 className="mt-3 text-3xl font-semibold text-court-ink md:text-4xl">
              Pickleball match analysis, step by step
            </h1>
            <p className="mt-4 max-w-3xl text-base leading-7 text-court-muted">
              Upload a recorded match, confirm the court, select your tracked player, and review
              movement analytics generated by the Court4 backend.
            </p>
          </div>
          <ButtonLink href="/matches/upload" className="self-start">
            <Upload aria-hidden="true" className="h-4 w-4" />
            Upload Match
          </ButtonLink>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-4">
        {workflow.map((step, index) => (
          <article key={step} className="rounded-md border border-court-line bg-white p-5 shadow-panel">
            <div className="flex items-center justify-between gap-3">
              <span className="grid h-9 w-9 place-items-center rounded-md bg-court-panel text-court-green">
                <CheckCircle2 aria-hidden="true" className="h-5 w-5" />
              </span>
              <span className="text-sm font-semibold text-court-muted">0{index + 1}</span>
            </div>
            <h2 className="mt-4 text-lg font-semibold text-court-ink">{step}</h2>
            <p className="mt-2 text-sm leading-6 text-court-muted">
              {workflowCopy[index]}
            </p>
          </article>
        ))}
      </section>

      <section className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-xl font-semibold text-court-ink">Recent matches</h2>
            <p className="text-sm text-court-muted">Local browser history only.</p>
          </div>
          <ButtonLink href="/matches" variant="secondary">
            View Matches
            <ArrowRight aria-hidden="true" className="h-4 w-4" />
          </ButtonLink>
        </div>
        <RecentMatches compact />
      </section>
    </div>
  );
}

const workflowCopy = [
  "Send one recorded pickleball match to the local Court4 backend.",
  "Use sampled frames to prepare the manual court-corner workflow.",
  "Confirm which tracked player should be analyzed.",
  "Review factual movement reports, trajectory, and heatmap artifacts.",
] as const;
